### ISSUE TITLE
Two Radial Graphs with same data on one page

### ISSUE THREAD

**Issue by vfi** [philogb/jit#119]
After creation two Radial Graphs on one page second one has non-clickable nodes.  You may drag it content without problem.
First graph is unaffected and works normally. 
If you make node ids unique problem vanishes.

**Comment by philogb** [comment]
is this using the same json data for both vizs? the ids should be unique per dataset **and** visualization.

**Comment by vfi** [comment]
Yes they are using same data. Does this mean I should generate unique ids even when I create new RGraph (via key word new)? Or may be there is way to create new viz (that will not conflict with existing graph)?

**Comment by philogb** [comment]
Even if created with new, the object ids must be unique per visualization.

On Mon, Aug 20, 2012 at 12:05 AM, Viktor Fedorov
notifications@github.comwrote:

> Yes they are using same data. Does this mean I should generate unique ids
> even when I create new RGraph (via key word new)? Or may be there is way to
> create new viz?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/philogb/jit/issues/119#issuecomment-7862142.

## 

Nicolas Garcia Belmonte - http://philogb.github.com/
