### ISSUE TITLE
jit logo?

### ISSUE THREAD

**Issue by twistedpair** [philogb/jit#130]
I'm adding JS detection for various new libraries to the Library Detector for Chrome. I noticed jit does not seem to have a favicon or logo of any kind on their site. I wanted to confirm there was no such thing since it would be nice to have artwork for the Chrome extension. Thanks.

**Comment by philogb** [comment]
Hey, that's true, we don't have a logo. selection.datavisualzation.ch uses a special image for the toolkit, maybe you'd want to use that as favicon?

http://selection.datavisualization.ch/

Thanks,
