### ISSUE TITLE
IE8 zero/zero error changing layout

### ISSUE THREAD

**Issue by ralphsmith80** [philogb/jit#139]
When there is a lot of node objects some of the nodes will have areas of 0. This causes and error in IE8 when changing layouts from squarify to slice and dice because the code [here](https://github.com/philogb/jit/blob/master/Source/Layouts/Layouts.TM.js#L496) and [here](https://github.com/philogb/jit/blob/master/Source/Layouts/Layouts.TM.js#L522) will result in a NaN object which IE8 doesn't like.

**Comment by philogb** [comment]
You fixed it :)
