### ISSUE TITLE
Space Tree - how to increase level

### ISSUE THREAD

**Issue by ramkumarsr** [philogb/jit#141]
Hi,

We are trying to use the Space tree and not able to increase the level of hierarchy. By default the tree structure is shown for 3 levels. My question is how to increase it to say for 8 levels?

Appreciate your help.

Ram

**Comment by philogb** [comment]
Hi, you can use the options `levelsToShow: 8` and `constrained: false` to show 8 levels regardless of whether the tree fits or not completely in the screen. More info here: http://philogb.github.com/jit/static/v20/Docs/files/Visualizations/Spacetree-js.html#ST

**Comment by ramkumarsr** [comment]
Thanks a lot for the clarification

With Regards,
Ramkumar SR
Mobile: +91 99622 06455
Extn: 53749
