### ISSUE TITLE
Bi-Directional Spacetree Request

### ISSUE THREAD

**Issue by mattjubb** [philogb/jit#15]
Hey, Would be really great if the spacetree could have children in more than direction. I know this is possible with Hypertree etc but the direction is decided for you. What I would like is the ability to add a child to the left or the right and then carry on from there.

**Comment by philogb** [comment]
Like this?

http://www.youtube.com/watch?v=6BxJDfJ3w2o

**Comment by mattjubb** [comment]
Yes!! does that mean its already possible? I couldn't find how to do it

**Comment by philogb** [comment]
It's already possible with the last revision of the toolkit. You'll need to download the source from GitHub.

You can check for this example then:

http://github.com/philogb/jit/blob/master/Tests/Spacetree/test10.js

**Comment by mattjubb** [comment]
one last quick question how do a build the source into a distribution .js
is it something like:
python build.py - that seems to just output all the javascript?

**Comment by philogb** [comment]
yes "python build.py > jit.js" or "python build.py Spacetree > jit.js" if you want just the code needed to instanciate a spacetree.
