### ISSUE TITLE
TreeMap tooltips misaligned in IE

### ISSUE THREAD

**Issue by eugenem** [philogb/jit#16]
doc.body.scrollTop isn't available in IE6+ when doctype is XHTML 1.0 Transitional

there is fix:
    initializeElements: function() {
...
            if(tipsAllow) {
                //Add mousemove event handler
                $addEvent(elem1, 'mousemove', function(e, win){
                    var tip = that.tip;
                    //get mouse position
                    win = win  || window;
                    e = e || win.event;
                    var doc = win.document;
                    // @EM added doc.documentElement for IE scrollTop availability
                    // doc = doc.html || doc.body;
                    doc = doc.documentElement || doc.html || doc.body;
                    var page = {
                        x: e.pageX || e.clientX + doc.scrollLeft,
                        y: e.pageY || e.clientY + doc.scrollTop
                    };

**Comment by philogb** [comment]
fixed in 2.0
