### ISSUE TITLE
Labels not cleared when data updated

### ISSUE THREAD

**Issue by unidesigner** [philogb/jit#18]
After creating a graph and a tree, I need to be able to change the underlying json data after some user interaction.

You see an example of this here:
http://connectome.ch/app/webroot/cwiki-vis/
Change the species.

The problem is, that the old labels are not removed.
The function RGraph.canvas.clear() removes the nodes and connections, but not the labels.

Thanks for this great toolkit!

**Comment by philogb** [comment]
Hi,

There;s a known bug about this that is solved in the trunk version of the
library, which is not yet released btw, but you can checkout the code at
github.

A workaround for this would be doing this for refreshing the SpaceTree data:

```
 var lbs = st.fx.labels;
 for (var label in lbs) {
     if (lbs[label]) {
      lbs[label].parentNode.removeChild(lbs[label]);
     }
 }

 st.fx.labels = {};
 st.loadJSON(json);
 st.compute();
 st.onClick(...) 
```

**Comment by unidesigner** [comment]
This worked out fine. Thanks!
