### ISSUE TITLE
Scrolling support for charts exceeding canvas bounds

### ISSUE THREAD

**Issue by sandesh247** [philogb/jit#2]
If there a large number of nodes in the tree (say a 100 children), they wont fit in the finite boundaries of the canvas element. Scrolling would enable us to view these hidden nodes.

**Comment by weltermann17** [comment]
I assume that you are talking about the spacetree. The fundamental idea of the spacetree is that it uses the available space to its best. On a left-oriented spacetree canvas-height can pose an ugly constraint forcing the user to "scroll" the content into the available space by clicking on one of the outer-most nodes. In my opinion scrolling the canvas would blur the characteristics of a spacetree. Maybe it would be better to automatically divide the subtree into n subtrees that each fit into the available space. Each subtree should be named automatically, for instance, "1 to 40 of 79" and "41 to 79 of 79". This way you would introduce new "artificial" levels but stay on the canvas. I think users are quite used to this kind of  "page 2 of 3" idioms. And it's easier to remember on which subtree "page" you were than the position of your vertical scrollbar.

**Comment by karlton** [comment]
scrolling support would be a greatgreat thing actually. implementing this "pagination" solutino does not make sense in a lot of cases.

**Comment by philogb** [comment]
I don't forget. I'm actively working on panning and zooming natively in all visualizations. Next push to GitHub should have that feature already http://www.youtube.com/watch?v=LBw74g6_xqw

**Comment by philogb** [comment]
The master branch of the project already includes the ability to zoom and pan for all visualizations, as you can see in this video: http://www.youtube.com/watch?v=CpXpAiZT1n0

**Comment by gossi** [comment]
oh that looks wonderful. I just raised issue #25 asking for zoom, but you were actually faster than me. Great Job!
