### ISSUE TITLE
Events on multiple widgets on the same page break

### ISSUE THREAD

**Issue by ariddle** [philogb/jit#20]
When I show multiple visualizations of the same type on the same page (within the same DOM) (e.g., 2 differently configured hypertrees, 3 differently configured treemaps, etc.) It seems that the event handling and therefore some labeling occurs only on the first encounter widget in the DOM.  For instance, if I hover over one treemap it changes the colors of the first treemap in the page.  Another example is that with 2 hypertrees, the labels of the second tree show up on the presentation of the first tree.

**Comment by philogb** [comment]
Fixed
