### ISSUE TITLE
Unable to align - LEFT the tree using Spacetree

### ISSUE THREAD

**Issue by cabela** [philogb/jit#21]
When align set to "left" something strange happens it is alligned something like ( right-bottom ) but definitely not left.
By left I expect that the root node is alligned on the left side of the black screen. I was unable to align it by any other alignment except center which is default. 
I would apreciate any help with this. My final task is to represent LAN network topology using SpaceTree.

**Comment by philogb** [comment]
Hi, could you please post this in the google group as I don't know yet if this is actually a bug or a feature request or a problem with a specific case? Also, could you attach in that post a picture of what you're seeing and a more detailed explanation of what you'd want to see? The google group's at http://groups.google.com/group/javascript-information-visualization-toolkit

**Comment by cabela** [comment]
This is a BUG since in the documentation it is mentioned that possible alignment is "left", "center", "right" and the default value is center :

align Whether the tree alignment is left, center or right.

unfortunatelly I have no idea how to publish this on google groups... unable to find out how.
