### ISSUE TITLE
Zoom ability

### ISSUE THREAD

**Issue by gossi** [philogb/jit#25]
I wish to have zoom controls, like in Google Maps. This is enabled by a settings property; setting zoom to true. The graph stays in the given rectangle. When zooming, either nodesize and/or levelsShown is manipulated.
Zoom controls could be simple +/- and additionally a scrollbar. Provide max and min values for width and height to the user, so they are able to build their own controls around the graph.

**Comment by philogb** [comment]
Yep, this is done in the current dev branch ;)
