### ISSUE TITLE
Spacetree: Extra connection line and overlap nodes

### ISSUE THREAD

**Issue by longsoft-dev** [philogb/jit#26]
Using current trunk (as of June 10, 2010) with the following test json data for spacetree example1.js, there will be some nodes overlapped with each other and when you click the Intranet node, there will be one extra connection line that connects to nothing.

{
      "id": "Applications", 
      "name": "Applications",
      "data": {}, 
      "children": [
        {
          "id": "PIS", 
          "name": "PIS",
          "data": {},
          "children": [
            {
              "id": "EasiMaps", 
              "name": "EasiMaps",
              "data": {},
              "children": []
            }
          ]
        },
        {
          "id": "Communications", 
          "name": "Communications",
          "data": {}, 
          "children": [
            {
              "id": "Email", 
              "name": "Email",
              "data": {}, 
              "children": [
                {
                  "id": "Exchange", 
                  "name": "Exchange",
                  "data": {},
                  "children": [
                    {
                      "id": "Outlook", 
                      "name": "Outlook",
                      "data": {},
                      "children": []
                    }
                  ]
                }
              ]
            },
            {
              "id": "Voice", 
              "name": "Voice",
              "data": {},
              "children": [
                {
                  "id": "Call Manager", 
                  "name": "Call Manager",
                  "data": {},
                  "children": []
                }
              ]
            }
          ]
        }, 
        {
          "id": "DM", 
          "name": "DM",
          "data": {}, 
          "children": [
            {
              "id": "Office", 
              "name": "Office",
              "data": {}, 
              "children": [
                {
                  "id": "Word", 
                  "name": "Word",
                  "data": {},
                  "children": []
                },
                {
                  "id": "Excel", 
                  "name": "Excel",
                  "data": {},
                  "children": []
                },
                {
                  "id": "Access", 
                  "name": "Access",
                  "data": {},
                  "children": []
                },
                {
                  "id": "PowerPoint", 
                  "name": "PowerPoint",
                  "data": {},
                  "children": []
                },
                {
                  "id": "Outlook", 
                  "name": "Outlook",
                  "data": {},
                  "children": []
                }
              ]
            }
          ]
        },
        {
          "id": "Finance", 
          "name": "Finance",
          "data": {},
          "children": [
            {
              "id": "HR Database",
              "name": "HR Database",
              "data": {},
              "children": []
            }
          ]
        }, 
        {
          "id": "Active Directory", 
          "name": "Active Directory",
          "data": {}, 
          "children": [
            {
              "id": "CdSync", 
              "name": "CdSync",
              "data": {}, 
              "children": [
                {
                  "id": "HR Database", 
                  "name": "HR Database",
                  "data": {}, 
                  "children": []
                },
                {
                  "id": "TokenExchange Database", 
                  "name": "TokenExchange Database",
                  "data": {}, 
                  "children": []
                }
              ]
            }
          ]
        }, 
        {
          "id": "Intranet", 
          "name": "Intranet",
          "data": {}, 
          "children": [
            {
              "id": "SharePoint", 
              "name": "SharePoint",
              "data": {},
              "children": [
                {
                  "id": "People Search", 
                  "name": "People Search",
                  "data": {},
                  "children": [
                    {
                      "id": "HR Database",
                      "name": "HR Database",
                      "data": {},
                      "children": []
                    }
                  ]
                },
                {
                  "id": "My HR", 
                  "name": "My HR",
                  "data": {},
                  "children": [
                    {
                      "id": "HR Database", 
                      "name": "HR Database",
                      "data": {}, 
                      "children": []
                    }
                  ]
                },
                {
                  "id": "Active Directory", 
                  "name": "Active Directory",
                  "data": {}, 
                  "children": []
                }
              ]
            },
            {
              "id": "DOG", 
              "name": "DOG",
              "data": {}, 
              "children": [
                {
                  "id": "Animal Database", 
                  "name": "Animal Database",
                  "data": {}, 
                  "children": []
                }
              ]
            }
          ]
        }, 
        {
          "id": "Highway", 
          "name": "Highway",
          "data": {}, 
          "children": []
        }, 
        {
          "id": "Calc", 
          "name": "Calc",
          "data": {}, 
          "children": [
            {
              "id": "Highway", 
              "name": "Highway",
              "data": {}, 
              "children": []
            }
          ]
        }
      ]
    }

**Comment by philogb** [comment]
As specified by the documentation here: http://thejit.org/docs/files/Loader-js.html#Loader the id of the nodes must be _unique_.
