### ISSUE TITLE
Build.py generated jit.js with incorrect syntax

### ISSUE THREAD

**Issue by longsoft-dev** [philogb/jit#27]
The current master branch as of Jun 11 2010:
line 7503 & 9809 & 13103 shouldn't have the comma: type: 'Circles',
line 11262 shouldn't have the extra comma too
line 13702 has extra comment end token "*/"

This nightly build seems totally broken in IE6

**Comment by philogb** [comment]
Thanks for the heads up, I've been moving things around to be able to write proper documentation.

You can try with the recent push, please confirm that things are working well,

**Comment by longsoft-dev** [comment]
Hi phil,
After you have fixed Icicle.js as pointed out in http://github.com/philogb/jit/issues/closed#issue/29/comment/279342, you can safely close this issue as I have tested it worked in IE then.

**Comment by philogb** [comment]
I think this is fixed now. You should check the demos at http://thejit.org/demos/
