### ISSUE TITLE
Graph layout with several types of edges

### ISSUE THREAD

**Issue by tayotas** [philogb/jit#30]
I'm working with a graph whit different kind of nodes and several types of edges between them.
I would like to display at the same time several types of edges, I would also like to distinguish those types using color or another graphical property. 
I wonder what is the best layout to use? Does the layout algorithms of Tulip accept several relationships?
In the tool is there an option that allows me to configure the display according to the type of edge or to the type of node? I mean, in a circle display, it is possible  to first put all the nodes of a type and later the nodes of another one?

Thanks in advance for your help.

Tayotas

**Comment by philogb** [comment]
For general graphs (and not trees) I would recommend the ForceDirected graph, it also implements different type of nodes and edges (with also different colors as you can see in this example http://thejit.org/static/v20/Jit/Examples/ForceDirected/example1.html ).I recommend you to take a look at the demos page, http://thejit.org/demos/ , and if you have further questions about this join the google group of the toolkit http://groups.google.com/group/javascript-information-visualization-toolkit
