### ISSUE TITLE
AreaChart filter failing when called a second time

### ISSUE THREAD

**Issue by hawkett** [philogb/jit#38]
Hi,

  I'm just getting started on infovis (which is very cool), looking at the AreaChart. I ran into a couple of issues with filtering. I'm calling the filter method like so

`areaChart.filter.apply(areaChart, selectedItems);`

to provide an array of labels to filter on.  The first call works fine, but subsequent calls with different `selectedItems` have no effect. I have verified that the busy flag is false prior to each call to `filter()`.

If I call `restore()` between each filter application then I can get it to work, but this presents some difficulties, because I need to wait for the `restore()` animation to complete before I can successfully call `filter()`, due to the busy flag.

Perhaps I'm missing something though - should I be able to make multiple calls to `filter()` with varying label names? If not, perhaps there is a way to chain a call to `restore()` followed by a call to `filter()`? 

For my use case I have six labels, first filter on a single label, and then add a second label to the filter - so the second call to `filter()` contains the first item and a new item - e.g.

`filter1 = ['label A']`

`filter2 = ['label A', 'label B']`

Cheers,

Colin

**Comment by philogb** [comment]
Hi,

Sorry for the late response. First of all, thank you very much for mentioning the bug, it's true that there's not a simple way to stack multiple filters. I just made a small change to the method signature to add a callback and enabled to filter multiple times.

https://github.com/philogb/jit/commit/afb8a389210654cd68aec2431b0a8b74c6252a6c

I hope this helps,

Nicolas.
