### ISSUE TITLE
Treemap: avoid creating boxes too small to see

### ISSUE THREAD

**Issue by timbunce** [philogb/jit#4]
For some data sets a lot of time can be spent processing boxes that are too small to see.

This can be fixed by adding the following 'precondition' check to createBox

```
// if box too small to be worth drawing then return empty string
if (coord.width * coord.height < 1) return "";
```

**Comment by philogb** [comment]
solved here:

http://github.com/philogb/jit/commit/3532396db05dc7e381b5abdf5fad611788ba1f76

Will be added in 1.1.3
