### ISSUE TITLE
Spacetree: Make treeFitsInCanvas check optional

### ISSUE THREAD

**Issue by beaugunderson** [philogb/jit#40]
In getRightLevelToShow a check is done to make sure the resulting tree fits in the canvas; if it does not the level is decreased until the resulting tree does fit.

I think this check should be optional--I should be able to control the number of levels displayed regardless of if they fit in the canvas (because the user is free to drag/zoom around).

**Comment by pmario** [comment]
would be nice for forceDirected too.

**Comment by philogb** [comment]
That currently exists in the Spacetree. Try adding:

```
{
   levelsToShow: n,
   constrained: false
}
```

where `n` is a number.
