### ISSUE TITLE
Hypertree: Rectangle Contains Function

### ISSUE THREAD

**Issue by Caleb-C** [philogb/jit#45]
Hypertree.Plot.NodeTypes.rectangle.contains calls the nodehelper for square instead of rectangle.

**Comment by philogb** [comment]
Thanks for mentioning it, I will try to fix it ASAP.

**Comment by philogb** [comment]
Thanks for mention it, I just pushed the fix:

https://github.com/philogb/jit/commit/6d0810df1bd9ff4d7aae11390c89d5ab1a4ed9fc
