### ISSUE TITLE
onMouseEnter does not work

### ISSUE THREAD

**Issue by lennartkoopmann** [philogb/jit#46]
the onMouseEnter event is never fired in my Chrome 7.0.517.41 on Linux with the following code:

```
var sb = new $jit.Sunburst({
  injectInto: 'visuals-spread-vis',
  levelDistance: 80,

  Node: {
    overridable: true,
    type: 'gradient-multipie'
  },

  NodeStyles: {
    enable: true,
    type: 'Native',
    stylesHover: {
      'color': '#fff'
    }
  },

  Events: {
    enable: true,
    onMouseEnter: function(node) {
      console.log("BLA");
    }
  },
});
```

Also tested this in Firefox 3.6.12 with no success.

**Comment by philogb** [comment]
Hi, I just tested Chrome 9, and Firefox 3.6 based on this example: https://github.com/philogb/jit/blob/master/Tests/Sunburst/test4.js#L634 and everything seems to work fine when I add an onMouseEnter callback method. Perhaps if you could provide me with a complete simple example then I can debug it closely. Please let me know if the problem persists.
