### ISSUE TITLE
Labels unaffected by Node-align

### ISSUE THREAD

**Issue by gossi** [philogb/jit#48]
With this snippet of configuration, nodes are aligned centric and labels are placed over it accordingly. Well if you change the node-align to left or right, the labels still stay centric and overlap the nodes. This happens with a Spacetree.

```
Node: {
    overridable: true,
    type: 'rectangle',
    autoWidth: true,
    autoHeight: true,
    color: '#ccc',
    align: 'center'
},
Label: {
    overridable: true,
    type: 'Native',
    color: '#000',
    size: 12
}
```

**Comment by philogb** [comment]
Thx for the report, fixed in the master branch
