### ISSUE TITLE
Bugfix in $jit.ST.Plot (for multitree)

### ISSUE THREAD

**Issue by gossi** [philogb/jit#50]
In the jit-2.0.0b.js (uncompressed version) it is line 9262, Class $jit.ST.Plot: Change line from:

return !root || orns.indexOf(elem.getData('orn')) > -1;

to:

return !root || orns.indexOf(node.getData('orn')) > -1;

to make it work again :)

**Comment by philogb** [comment]
Added that to the master branch, thanks!
