### ISSUE TITLE
TreeMap : computed node height can be negative

### ISSUE THREAD

**Issue by clementdenis** [philogb/jit#54]
If a subnode is small enough, the computed display height can be negative. It creates a weird rendering on Firefox, Chrome, and produces an error on IE.

The problem is in Layouts.TM.js, in the [computePositions function](https://github.com/philogb/jit/blob/master/Source/Layouts/Layouts.TM.js#L256)
<code>height = chi.getData('height', prop) - offst - config.titleHeight,</code>

If chi.getData('height', prop) is smaller than config.titleHeight, the computed height is negative.

I just added this line as a workaround (the node is not displayed, but the rendering is ok in all browsers)
<code>height = height < 0 ? 0 : height;</code>

**Comment by philogb** [comment]
Thanks a lot for your feedback, I will try to fix this issue for the next release :)

**Comment by philogb** [comment]
Fixed in the master branch :)
