### ISSUE TITLE
Treemap: change box filling order from towards top right, to towards bottom right

### ISSUE THREAD

**Issue by timbunce** [philogb/jit#6]
Can the logic be changed to put the smaller boxes towards the bottom/right?

That not only seems more natural, it would also improve the appearence by avoiding some top boxes not starting at the very top.

**Comment by philogb** [comment]
This was fixed in this commit:

http://github.com/philogb/jit/commit/5b106d98c227c250330328c408642c5fd49e64da

These changes will be added for version 1.1.3
