### ISSUE TITLE
Treemap changes order of children elements in the tree

### ISSUE THREAD

**Issue by webholics** [philogb/jit#9]
The treemap changes the order of the children elements in the tree.
This is really a minor issue but should be considered to be fixed because it is not replicable from outside what the treemap object does.
One of my implementations relied on the order of those children elements, so this behavior was really a mess. I had the clone the whole tree over and over again. And I don't think this is necessary.

**Comment by philogb** [comment]
the JSON tree? I should have pointed out that the JSON tree is modified when used with the TreeMap. I wouldn't like to add an Object cloning algorithm to the visualization unless it's really necessary. I just think that pointing that out in the documentation should suffice.

**Comment by webholics** [comment]
isn't it possible to not modify the tree at all?
But yes otherwise it should be mentioned in the documentation.

**Comment by philogb** [comment]
Hi, the new version of the toolkit (2.0.0a) doesn't change the JSON data when creating a new TreeMap visualization. If you have the time to take a look at the new version check for any inconsistencies and re-open this issue if you encounter new problems. The library's at http://thejit.org/
